name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: PyBuilder Action
      uses: pybuilder/build@v9
      with:
        pyb-args: "-E ci -v"
