name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to pypi
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: PyBuilder Action
      uses: pybuilder/build@v9
      with:
        pyb-args: "-E ci -v"
        pyb-extra-args: "clean publish upload"
