name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to pypi
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: PyBuilder Action
      uses: pybuilder/build@v9
      with:
        pyb-args: "-E ci -v"
        pyb-extra-args: "clean publish upload"
